### ISSUE TITLE
Arduino Library Requirements

### ISSUE THREAD

**Issue by DaneEvans** [oalam/isometryx#1]
So we're all working with the same libraries, @oalam can you update with what you're using, and probably put this in the repo somewhere

The following allows a compile, I haven't tested it on HW
- Adafruit BluefruitLE nRF51       version ?
- Adafruit GFX Library                 version ?
- Adafruit SSD1306                     version ?
- HX711 Arduino Library     Bogdan Necula  version?

**Comment by oalam** [comment]
I've written them in the README.md
